var data  =
{
    "see years ago": "Ages ago",
    "hairy": "'Airy",
    "hello": "Alrigh'",
    "etc": "An' tha'",
    "Mad": "Annoyed",
    "Old": "Antiduian",
    "Hermaphrodite": "Aphrodite",
    "a disjunct indicating that the concurrent sentence is almost certainly bollocks": "Apparently",
    "something for your eyes to look at": "Art",
    "exploding": "Atomic",
    "Babylon": "Baba",
    "worse": "Badder",
    "A Hurricane Typhoon or tornado": "Bad Wind",
    "ptosis": "Big eyelids",
    "expendable": "Binable",
    "manliness signs that one is a man: When meeting a tranny you should look for signs of blokage": "Blokage",
    "bon bons": "Bom boms",
    "Roswell": "Boswell",
    "head skull": "Brain case",
    "enema colonic irrigation: No bum tubes though.": "Bum tube",
    "bundled in: I don't wanna be bungled in": "Bungled in",
    "put on: I'll bung a song on then": "Bung on",
    "chaise longues": "Chaise londges",
    "any oriental nationality": "Chinese",
    "A primate trained for NASA space program in 1959": "Chimpanaut",
    "a bad beating: Leroy gave us a right good clackerin'.": "Clackering",
    "Clive Owen": "Clive Warren",
    "the wheels on an office operator chair": "Coaster wheel things",
    "cauliflower as in \"Colly Osborne\"": "Colly",
    "came: He had helmet on but his head come off.": "Come",
    "consistency": "Condensity",
    "crops": "Croppage",
    "farming": "Cropping",
    "cyclops": "Cyclop",
    "ersatz / improper: the thing is right if you have a lot of something you also have a lot of demick ones what aren't properly.": "Demick/demicky",
    "Dictionary": "a book with words in",
    "Descartes": "Diskartis",
    "insult": "Diss",
    "drawn": "Drawned",
    "swearing": "Effin' 'n' jeffin'",
    "Egyptian man": "Egypt bloke",
    "Elephantiasis": "Elephantitis",
    "facial": "Face rub",
    "messing around": "faffin'",
    "unhappy": "Fed up",
    "aquarium": "Fish shop",
    "rubbish": "Flumpf",
    "food": "Foodage",
    "disabled person": "Forrest Gump",
    "fear: he had a look of frightendness on his face": "Frightenedness",
    "frozen": "froze",
    "problems": "Fuckerage",
    "problem": "Fuckerage",
    "group of animals": "Gang",
    "filth": "Glunge",
    "says": "Goes",
    "spitting: the octopus was gozzin' about everywhere": "Gozzin'",
    "primitive photosynthetic life forms: In the beginning air created the greenness": "Greenness",
    "grip purchase: there's a lot of grippage on the side of the building": "Grippage",
    "having sex: we were on holiday and we were havin' it away an' that...": "Havin' it away",
    "an angle off straight: ...went off at a hypotenuse.": "Hypotenuse",
    "Antarctica": "Iceland",
    "arthropod": "Insect",
    "isn't": "In't",
    "Jamaican": "Jamaican fella",
    "tricked": "Kidded",
    "penis": "Knob",
    "Karl's favourite insult": "Knobhead",
    "around in the area: turned out.. a monkey was knockin' about": "Knockin' about",
    "wasabi: I'm serving some right rubbish tonight give 'em some of that kusabi": "Kusabi",
    "a type of river": "Lake",
    "lackadaisical": "Laxidaisical",
    "lax": "Laxidaisical",
    "teach": "Learn",
    "masseur / masseuse": "Leg rubber (professional)",
    "cross between limp and flimsy.": "Limsy",
    "totally meaningless adjective often used to describe characters in Karl's anecdotes or stories (e.g. 'little fella in a wheelchair').": "Little",
    "any homosexual male not necessarily a small one: there was this little gay fella...": "Little gay fella",
    "individuals with surnames beginning with \"Mac\"": "Macs",
    "mother": "Mam",
    "grandmother": "Mam's mam",
    "a cross between a human and a moth.": "Manmoth",
    "weak \"can't handle anything\" \"get ill easy\": they're coming out all mardy": "Mard/Mardy",
    "my / a consciousness exogenous to one's brain: Am I me or me brain?": "Me",
    "crazy": "Mentalist",
    "minimalistic: A coupla years back people went miminalistic": "Miminalistic",
    "the gene that precipitates a moaning of the worries in the worry hole": "Moan gene",
    "a characteristic of people who live underground": "Molish",
    "covered in moles: Auntie Nora's back is moly": "Moly",
    "any nonhuman primate usually a chimpanzee": "Monkey",
    "mongooses": "Mongs",
    "mongoose": "Mong",
    "slumped slouched: moped over in a wheelchair": "Moped over",
    "an exorcist": "Mr. Exorcist",
    "drink quickly down (a drink): They've got a coffee with ice in so they can neck it.": "Neck",
    "anything that has ever been written on the internet at some point": "News",
    "embarrassing because of the insight it shines on one's thinking. This is Karl's reasoning for why Karl will not use cubicle toilets to avoid using urinals next to \"little gay fellas\" and why \"the two kids with big heads and webbed fingers\" were not friends.": "Obvious",
    "see years ago": "Olden days (the)",
    "other more evolved forms of life than greenness. From the greenness came otherness": "Otherness",
    "brother or sister": "Our kid",
    "Karls excuse to prove Suzanne wrong as he had to pay an £80 call out charge for a broken fuse which he could have easily fixed. Suzanne: Karl call someone out. Karl: Oven": "Oven",
    "Overwhelmed daunted: I'd probably be overfaced by that apple. It's too much.": "Overfaced",
    "alpaca": "Palaco",
    "natives of Papua New Guinea: these Papa People right...": "Papa people",
    "pet peeve": "Pet hate",
    "crumpet": "Pikelet",
    "ear plugs": "Plunge things",
    "broach": "Posh badge",
    "causing problems": "Probleming",
    "Prosperity coming from Chinese Star Gods": "Prosperarity",
    "thinks well of: everyone's ravin' about Einstein an' tha'.": "Ravin' about",
    "reminded: now that you've remembered me that...": "Remembered",
    "replenishing: I needed to replemish 'cos I was so tired": "Replemishing",
    "Robert: Rob'er Plant": "Rob'er",
    "a quiz where \"cryptic\" clues and initials are given for a musical artist to be guessed a shameless ripoff of the popular television show Blockbusters.": "Rockbusters",
    "wrong 'un ne'erd'well: she was a rum 'un": "Rum 'un",
    "rummaging: he started rummanging": "Rummanging",
    "borstal a place for the animals with a rough upbringing": "Sanctuary",
    "cry": "Scrike",
    "scruffy": "Scruffily",
    "shook": "Shuck",
    "loads": "Six billion",
    "school": "Skewl",
    //"when you're sort of shutdown": "Sleep",
    "slug matter": "Sluggage",
    "sneaky untrustworthy: there's always a little snidey one.": "Snidey",
    "squeezed; squeeze (past imperfect): he came in at one o'clock and squoze it then!": "Squoze",
    "squeezed; squeeze (past perfect): That's before the stress of you know having heads squozed an' that": "Squozed",
    "Karl's girlfriend": "Suzanne",
    "Swedish woman": "Swede woman",
    "tension": "Tenseness",
    "testosterone": "Testerone",
    "testicles": "Testi",
    "Congo": "The Conga",
    "Wild West": "The Western",
    "these": "Them",
    "those": "Them",
    "theft": "Thetht",
    "robbery": "Thetht",
    "careful with money not generous.": "Tight",
    "hit": "Thump",
    'punch': "Thump",
    "Knock": "Tink",
    "tongue": "Tong",
    "tupperware": "Tubberware",
    "Tea": "Twinings",
    "ugly": "Uglely",
    "uncomfortable": "Uncomfy",
    "promoted: they get sort of... what's the word... sort of uppered too early": "Uppered",
    "web: ...floating around on a bit of webbage": "Webbage",
    "something that is interesting or odd to Karl \"thing's you don't see\"": "Weird",
    "an old female ghost with drooping breasts: I said she might end up becoming a wewe.": "Wewe",
    "whatnot": "What have yer",
    "hername: when Karl can't find the right word he says this whether it's a woman man place event etc.: I went to what'shername... barley street": "What's",
    "moaning rebuke criticism: I don't understand this whingingness.": "Whingingness",
    "reveal in a startling or impertinent manner: she whopped 'em out and he started suckin' on 'em an' that": "Whop",
    "nillilycarefree: but you just said it willynillily": "Willy",
    "The Earth The Earth is our world; it's the World": "World (the)",
    "the part of the brain where problems are contained. It can either be filled with a few big worries or many smaller worries but all brains must fill it somehow.": "Worry hole",
    "written: someone had wroteduh!": "Wroted",
    "the radio station Karl was discovered on": "XFM",
    "some time between the origin of the universe and a couple of years ago; also ages ago and (the) olden days.": "Years ago"
}
var htmlCollToArr           = (coll) => [].slice.call(coll); //converts htmlCollectiondocument to array
var isTextNode              = (node) => node.nodeType === 3 && node.nodeValue.trim();



String.prototype.capitalizeFirstLetter = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}
String.prototype.lowercaseFirstLetter = function() {
    return this.charAt(0).toLowerCase() + this.slice(1);
}
var numberOfReplacementsPerformed = 0;
$(function() {
  var elements                = htmlCollToArr(document.getElementsByTagName('*'));
  elements.map( (element) => {
    htmlCollToArr(element.childNodes)
      .filter(isTextNode)
      .map( (node) => {
        let text = node.nodeValue;
        let replacedText = text;
        Object.keys(data).map( (key) => {
           let re = new RegExp('(^|[ ])('+key+')($|[.!?\\- ])' ,"gi");
           replacedText = replacedText.replace(re, function ( match, spaceBefore, text, spaceAfter ) {
             return spaceBefore + ( match === match.toLowerCase() ? data[key].lowercaseFirstLetter() :  data[key].capitalizeFirstLetter() ) + spaceAfter;
           });
        })
        if (replacedText !== text) {
          element.replaceChild(document.createTextNode(replacedText), node);
          numberOfReplacementsPerformed++;
        }
       })
      })
  console.log("Replaced ", numberOfReplacementsPerformed, " words");
});
